name: demo_variables_entorno

services:

  # crea una imagen común para todos los demos
  crear_imagen:
    build: .
    image: demo_entornos 

  # cada contenedor pone a prueba distintas interpolaciones
  entornos:
    image: demo_entornos 
    environment:
      VARIABLE_PYTHON: "${VARIABLE}"
    depends_on:
      crear_imagen:
        condition: service_completed_successfully

  entornos_default:
    image: demo_entornos 
    environment:
      VARIABLE_PYTHON: "${VARIABLE:-'valor predefinido'}"
    depends_on:
      crear_imagen:
        condition: service_completed_successfully

  entornos_error:
    image: demo_entornos 
    environment:
      VARIABLE_PYTHON: "${VARIABLE?'Error: variable no inicializada'}"
    depends_on:
      crear_imagen:
        condition: service_completed_successfully

  entornos_sustituir:
    image: demo_entornos 
    environment:
      VARIABLE_PYTHON: "${VARIABLE:+Sustituido}"
    depends_on:
      crear_imagen:
        condition: service_completed_successfully