
services:

  python-docs:
    image:  mkdocs-local:python
    build:  .
    container_name: python-docs
    ports:
      - "${PORT:-8000}:8000"
    security_opt: 
      - label=disable
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true


