name: integrador
services:

  tabla_flet:    
    build: demo/
    image: tabla_flet-web:v1
    ports:
      - ${PUERTO_FRONT:-8000}:8000
    depends_on: 
      base_datos:
          restart: true
          condition: service_healthy
          required: true
    restart: always
    environment:
      TAG_LENGUAJE: "ES_AR"
      POSTGRES_DB:       ${NOMBRE_DB:-personas_tabla}
      POSTGRES_DOMINIO:  base_datos
      POSTGRES_USER:     ${USUARIO:-noname}
      # POSTGRES_PASSWORD: ${PASS:-123456}
      POSTGRES_PASSWORD_FILE: /run/secrets/secreto
    secrets:
      - secreto
    networks:
      - red-tablas-personas


  base_datos:
    restart: always
    image: postgres:17.2-bookworm     
    environment:
      POSTGRES_USER:     ${USUARIO:-noname}
      POSTGRES_PASSWORD_FILE: /run/secrets/secreto
      POSTGRES_DB:       ${NOMBRE_DB:-personas_tabla}
    ports:
      - ${PUERTO_DB:-5432}:5432
    volumes:
      - volumen_db:/var/lib/postgresql/data
    secrets:
      - secreto
    networks:
      - red-tablas-personas
    healthcheck:  
      test: ["CMD-SHELL", "psql -U ${USUARIO:-noname} -d ${NOMBRE_DB:-personas_tabla} -c 'SELECT 1' || exit 1"]  
      interval: 10s
      timeout: 60s
      retries: 5


networks:
  red-tablas-personas:

volumes:
  volumen_db:

secrets:
  secreto:
    file: ./secreto.txt    
    # file: $HOME/secreto.txt   